### ISSUE TITLE
Refine categories data, depending on the design priority

### ISSUE THREAD

**Issue by nusa-venture-admin** [nusaventure/nusaventure-backend#25]
- Prioritize featured categories such as Beach, Mountain, dsb according to the UI design
- Model Category has featured boolean

Prioritized categories:

Historical Sites
Beach
Amusement Park
Campground
Art Gallery
Mountain

Add more as needed

----------------
- [x] di model `Category`, tambah kolom
```
isFeatured boolean default false
position int nullable
```

- [x] buat route baru `/categories/featured`
Ambil category yang `isFeatured = true` dan order by `position` asc

- [x] di seeder categories tambahkan `isFeatured` dan `position` sesuai di figma

![Image](https://github.com/user-attachments/assets/12e5091a-411f-44ac-b27c-f8361fefa52f)

**Comment by mhaidarhanif** [comment]
@hanifptw @mailfaruqi Endpoint places features sudah jadi ya, bisa dipakai di hero
