### ISSUE TITLE
Design API endpoint

### ISSUE THREAD

**Issue by nusa-venture-admin** [nusaventure/nusaventure-backend#5]

**Comment by azizramdan** [comment]
| Endpoint         | HTTP     | Description                                                             |
| ---------------- | -------- | ----------------------------------------------------------------------- |
| `/countries`     | `GET`    | Get all countries. Filters: search by name                              |
| `/islands`       | `GET`    | Get all islands. Filters: search by name, country id                    |
| `/cities`        | `GET`    | Get all cities. Filters: search by name, country id, island id          |
| `/places`        | `GET`    | Get all places. Filters: search by name, country id, island id, city id |
| `/places/:slug`  | `GET`    | Get place by id                                                         |
| `/auth/register` | `POST`   | Register                                                                |
| `/auth/login`    | `POST`   | Login                                                                   |
| `/plans`         | `GET`    | Get all user's plans                                                    |
| `/plans/:id`     | `GET`    | Get detail user's plan                                                  |
| `/plans`         | `POST`   | Create new plan                                                         |
| `/plans/:id`     | `PATCH`  | Update user's plan                                                      |
| `/plans/:id`     | `DELETE` | Delete user's plan                                                      |
