### ISSUE TITLE
API for for saved places

### ISSUE THREAD

**Issue by nusa-venture-admin** [nusaventure/nusaventure-backend#58]
- [x] `savedPlaces` table
- userId
- placeId

unique columns (userId, placeId)

- [x] GET `/saved-places`
```ts
success: bool
data: Array<Place>
```

- [x] POST `/saved-places`
```ts
body: {
    placeId: string
}
```

- [x] DELETE `/saved-places`
```ts
body: {
    placeId: string
}
```

**Comment by azizramdan** [comment]
kalo ada yang kurang bisa ditambah/ubah mas @myusufuw
