### ISSUE TITLE
Design database schema, put into Prisma Schema

### ISSUE THREAD

**Issue by nusa-venture-admin** [nusaventure/nusaventure-backend#6]

**Comment by azizramdan** [comment]
countries
- id
- name
- imageUrl

islands
- id
- countryId
- name
- imageUrl

cities
- id
- islandId
- name
- imageUrl

categories
- id
- name

places
- id
- cityId
- categoryId
- address
- title
- slug
- description
- imageUrl
- latitude
- longitude

images
- id
- placeId
- url
- title
- description

users
- id
- firstName
- lastName
- email
- username

plans
- id
- userId
- startDate
- endDate
- title
- status

planPlaces
- id
- placeId
- position
- startDate
- endDate
